version: "3.9"

services:
    db:
        image: postgres:14.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
    web:
        build: .
        volumes: 
            - .:/app/
        ports:
            - "8000:8000"
        depends_on: 
            - db

volumes:
  media:
  static:
  postgres_data: